In [29]:
import pandas as pd
import math

In [30]:
df = pd.read_csv("data.csv")

In [31]:
df

       age  income student credit_rating buys_computer
0     <=30    high      no          fair            no
1     <=30    high      no     excellent            no
2   30..40    high      no          fair           yes
3      >40  medium      no          fair           yes
4      >40     low     yes          fair           yes
5      >40     low     yes     excellent            no
6   30..40     low     yes     excellent           yes
7     <=30  medium      no          fair            no
8     <=30     low     yes          fair           yes
9      >40  medium     yes          fair           yes
10    <=30  medium     yes     excellent           yes
11  30..40  medium      no     excellent           yes
12  30..40    high     yes          fair           yes
13     >40  medium      no     excellent            no
14    <=30    high     yes          fair            no
15    <=30     low      no          fair            no
16    <=30     low      no     excellent            no
17     >40     low     yes          fair           yes
18    <=30  medium      no     excellent           yes
19     >40    high     yes          fair            no
20  30..40  medium      no     excellent           yes
21     >40  medium      no          fair           yes
22  30..40     low     yes          fair           yes
23     >40    high      no     excellent            no
24    <=30  medium     yes          fair           yes
25     >40  medium     yes     excellent           yes
26    <=30     low      no          fair            no
27    <=30    high      no          fair           yes
28  30..40     low     yes          fair            no
29    <=30  medium      no     excellent            no
30     >40     low     yes     excellent           yes
31     >40  medium      no          fair            no
32  30..40     low     yes     excellent            no
33     >40    high      no     excellent           yes
34     >40     low      no          fair           yes
35     >40  medium      no          fair           yes
36  30..40    high      no          fair           yes
37     >40     low      no     excellent           yes
38  30..40     low     yes     excellent            no
39  30..40    high      no          fair            no
40    <=30    high     yes          fair            no
41    <=30     low      no     excellent            no
42     >40  medium     yes          fair           yes
43  30..40  medium     yes     excellent            no
44     >40  medium      no          fair           yes
45    <=30     low      no          fair           yes
46     >40  medium      no          fair            no
47    <=30    high     yes          fair           yes
48    <=30    high      no          fair           yes
49     >40     low     yes     excellent            no
50     >40  medium     yes     excellent            no

In [32]:
columnDict = {}
for col in df.columns:
    columnDict[col] = df[col].unique()

In [33]:
columnDict

{'age': array(['<=30', '30..40', '>40'], dtype=object),
 'income': array(['high', 'medium', 'low'], dtype=object),
 'student': array(['no', 'yes'], dtype=object),
 'credit_rating': array(['fair', 'excellent'], dtype=object),
 'buys_computer': array(['no', 'yes'], dtype=object)}

In [34]:
count = df['buys_computer'].value_counts()

In [35]:
count

buys_computer
yes    28
no     23
Name: count, dtype: int64

In [36]:
InfoD = round(-(count[0]/len(df)) * math.log(count[0]/len(df) , 2) -(count[1]/len(df)) * math.log(count[1]/len(df) , 2) , 3)

C:\Users\HP\AppData\Local\Temp\ipykernel_3844\1628571851.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  InfoD = round(-(count[0]/len(df)) * math.log(count[0]/len(df) , 2) -(count[1]/len(df)) * math.log(count[1]/len(df) , 2) , 3)

In [37]:
InfoD

0.993

# Finding Root Node

In [38]:
def findInfo(valueDict, col, key):
    countY = 0
    for i in range(len(df)):
        if df[col][i] == key:
            if df['buys_computer'][i] == 'yes':
                countY += 1
    return (-(countY/valueDict[key]) * math.log(countY/valueDict[key] , 2) -((valueDict[key] - countY)/valueDict[key]) * math.log((valueDict[key] - countY)/valueDict[key] , 2))

column = df.columns.tolist()
column.pop()
root = ''
maxGain = -1
for col in column:
    valueDict = {}
    for row in range(len(df)):
        if df[col][row] not in valueDict:
            valueDict[df[col][row]] = 1
        else:
            valueDict[df[col][row]] += 1
        
    info = 0
    for key in valueDict.keys():
        info += round((valueDict[key]/len(df))*findInfo(valueDict, col,key) , 3) 
    gain = round(InfoD - info, 3)
    print(col," ", '->'," ",gain)
    if gain > maxGain:
        maxGain = gain
        root = col

age   ->   0.017
income   ->   0.011
student   ->   0.001
credit_rating   ->   0.029

In [39]:
root

'credit_rating'

In [40]:
maxGain

0.029